# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BossUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BossUi(object):
    def setupUi(self, BossUi):
        BossUi.setObjectName("BossUi")
        BossUi.resize(1340, 860)
        self.label = QtWidgets.QLabel(BossUi)
        self.label.setGeometry(QtCore.QRect(-10, -10, 1351, 881))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("FBG.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(BossUi)
        self.pushButton.setGeometry(QtCore.QRect(710, 690, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(88, 232, 227);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(BossUi)
        self.pushButton_2.setGeometry(QtCore.QRect(930, 690, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(BossUi)
        self.textBrowser.setGeometry(QtCore.QRect(650, 30, 321, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background:transparent;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(BossUi)
        self.textBrowser_2.setGeometry(QtCore.QRect(970, 30, 321, 81))
        self.textBrowser_2.setStyleSheet("background:transparent;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_2 = QtWidgets.QLabel(BossUi)
        self.label_2.setGeometry(QtCore.QRect(-170, -130, 631, 531))
        self.label_2.setStyleSheet("background:transparent;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Fgif.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(BossUi)
        QtCore.QMetaObject.connectSlotsByName(BossUi)

    def retranslateUi(self, BossUi):
        _translate = QtCore.QCoreApplication.translate
        BossUi.setWindowTitle(_translate("BossUi", "Dialog"))
        self.pushButton.setText(_translate("BossUi", "START"))
        self.pushButton_2.setText(_translate("BossUi", "STOP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BossUi = QtWidgets.QDialog()
    ui = Ui_BossUi()
    ui.setupUi(BossUi)
    BossUi.show()
    sys.exit(app.exec_())
